
/*
 * All ECMA-262 primordials organized by category
 * Each entry defines: globals, instanceMethods, staticMethods (in alphabetical order)
 */

/**
 * @typedef {object} PrimordialCategory
 * @property {string[]} globals
 * @property {string[]} instanceMethods
 * @property {string[]} staticMethods
 * @property {string[]} [instanceProperties]
 * @property {string[]} [staticProperties]
 * @property {string[]} [wellKnownSymbols]
 */

/** @type {Record<string, PrimordialCategory>} */
export const primordials = {
	AggregateError: {
		globals: ['AggregateError'],
		instanceMethods: [],
		staticMethods: [],
	},
	Array: {
		globals: ['Array'],
		instanceMethods: [
			'at',
			'concat',
			'copyWithin',
			'entries',
			'every',
			'fill',
			'filter',
			'find',
			'findIndex',
			'findLast',
			'findLastIndex',
			'flat',
			'flatMap',
			'forEach',
			'includes',
			'indexOf',
			'join',
			'keys',
			'lastIndexOf',
			'map',
			'pop',
			'push',
			'reduce',
			'reduceRight',
			'reverse',
			'shift',
			'slice',
			'some',
			'sort',
			'splice',
			'toLocaleString',
			'toReversed',
			'toSorted',
			'toSpliced',
			'toString',
			'unshift',
			'values',
			'with',
		],
		staticMethods: [
			'from',
			'fromAsync',
			'isArray',
			'of',
		],
	},
	ArrayBuffer: {
		globals: ['ArrayBuffer'],
		instanceMethods: [
			'resize',
			'slice',
			'transfer',
			'transferToFixedLength',
		],
		instanceProperties: [
			'byteLength',
			'detached',
			'maxByteLength',
			'resizable',
		],
		staticMethods: ['isView'],
	},
	AsyncGenerator: {
		globals: [],
		instanceMethods: [
			'next',
			'return',
			'throw',
		],
		staticMethods: [],
	},
	AsyncGeneratorFunction: {
		globals: ['AsyncGeneratorFunction'],
		instanceMethods: [],
		staticMethods: [],
	},
	AsyncIterator: {
		globals: ['AsyncIterator'],
		instanceMethods: [
			'drop',
			'every',
			'filter',
			'find',
			'flatMap',
			'forEach',
			'map',
			'reduce',
			'some',
			'take',
			'toArray',
		],
		staticMethods: ['from'],
	},
	Atomics: {
		globals: ['Atomics'],
		instanceMethods: [],
		staticMethods: [
			'add',
			'and',
			'compareExchange',
			'exchange',
			'isLockFree',
			'load',
			'notify',
			'or',
			'store',
			'sub',
			'wait',
			'waitAsync',
			'xor',
		],
	},
	BigInt: {
		globals: ['BigInt'],
		instanceMethods: [
			'toLocaleString',
			'toString',
			'valueOf',
		],
		staticMethods: [
			'asIntN',
			'asUintN',
		],
	},
	Boolean: {
		globals: ['Boolean'],
		instanceMethods: [
			'toString',
			'valueOf',
		],
		staticMethods: [],
	},
	DataView: {
		globals: ['DataView'],
		instanceMethods: [
			'getBigInt64',
			'getBigUint64',
			'getFloat16',
			'getFloat32',
			'getFloat64',
			'getInt8',
			'getInt16',
			'getInt32',
			'getUint8',
			'getUint16',
			'getUint32',
			'setBigInt64',
			'setBigUint64',
			'setFloat16',
			'setFloat32',
			'setFloat64',
			'setInt8',
			'setInt16',
			'setInt32',
			'setUint8',
			'setUint16',
			'setUint32',
		],
		instanceProperties: [
			'buffer',
			'byteLength',
			'byteOffset',
		],
		staticMethods: [],
	},
	Date: {
		globals: ['Date'],
		instanceMethods: [
			'getDate',
			'getDay',
			'getFullYear',
			'getHours',
			'getMilliseconds',
			'getMinutes',
			'getMonth',
			'getSeconds',
			'getTime',
			'getTimezoneOffset',
			'getUTCDate',
			'getUTCDay',
			'getUTCFullYear',
			'getUTCHours',
			'getUTCMilliseconds',
			'getUTCMinutes',
			'getUTCMonth',
			'getUTCSeconds',
			'setDate',
			'setFullYear',
			'setHours',
			'setMilliseconds',
			'setMinutes',
			'setMonth',
			'setSeconds',
			'setTime',
			'setUTCDate',
			'setUTCFullYear',
			'setUTCHours',
			'setUTCMilliseconds',
			'setUTCMinutes',
			'setUTCMonth',
			'setUTCSeconds',
			'toDateString',
			'toISOString',
			'toJSON',
			'toLocaleDateString',
			'toLocaleString',
			'toLocaleTimeString',
			'toString',
			'toTimeString',
			'toUTCString',
			'valueOf',
		],
		staticMethods: [
			'now',
			'parse',
			'UTC',
		],
	},
	decodeURI: {
		globals: ['decodeURI'],
		instanceMethods: [],
		staticMethods: [],
	},
	decodeURIComponent: {
		globals: ['decodeURIComponent'],
		instanceMethods: [],
		staticMethods: [],
	},
	encodeURI: {
		globals: ['encodeURI'],
		instanceMethods: [],
		staticMethods: [],
	},
	encodeURIComponent: {
		globals: ['encodeURIComponent'],
		instanceMethods: [],
		staticMethods: [],
	},
	Error: {
		globals: ['Error'],
		instanceMethods: ['toString'],
		staticMethods: [
			'captureStackTrace',
			'isError',
		],
	},
	eval: {
		globals: ['eval'],
		instanceMethods: [],
		staticMethods: [],
	},
	EvalError: {
		globals: ['EvalError'],
		instanceMethods: [],
		staticMethods: [],
	},
	FinalizationRegistry: {
		globals: ['FinalizationRegistry'],
		instanceMethods: [
			'register',
			'unregister',
		],
		staticMethods: [],
	},
	Function: {
		globals: ['Function'],
		instanceMethods: [
			'apply',
			'bind',
			'call',
			'toString',
		],
		staticMethods: [],
	},
	Generator: {
		globals: [],
		instanceMethods: [
			'next',
			'return',
			'throw',
		],
		staticMethods: [],
	},
	GeneratorFunction: {
		globals: ['GeneratorFunction'],
		instanceMethods: [],
		staticMethods: [],
	},
	globalThis: {
		globals: ['globalThis'],
		instanceMethods: [],
		staticMethods: [],
	},
	Infinity: {
		globals: ['Infinity'],
		instanceMethods: [],
		staticMethods: [],
	},
	isFinite: {
		globals: ['isFinite'],
		instanceMethods: [],
		staticMethods: [],
	},
	isNaN: {
		globals: ['isNaN'],
		instanceMethods: [],
		staticMethods: [],
	},
	Iterator: {
		globals: ['Iterator'],
		instanceMethods: [
			'drop',
			'every',
			'filter',
			'find',
			'flatMap',
			'forEach',
			'map',
			'reduce',
			'some',
			'take',
			'toArray',
		],
		staticMethods: ['from'],
	},
	JSON: {
		globals: ['JSON'],
		instanceMethods: [],
		staticMethods: [
			'isRawJSON',
			'parse',
			'rawJSON',
			'stringify',
		],
	},
	Map: {
		globals: ['Map'],
		instanceMethods: [
			'clear',
			'delete',
			'entries',
			'forEach',
			'get',
			'has',
			'keys',
			'set',
			'values',
		],
		instanceProperties: ['size'],
		staticMethods: ['groupBy'],
	},
	Math: {
		globals: ['Math'],
		instanceMethods: [],
		staticMethods: [
			'abs',
			'acos',
			'acosh',
			'asin',
			'asinh',
			'atan',
			'atan2',
			'atanh',
			'cbrt',
			'ceil',
			'clz32',
			'cos',
			'cosh',
			'exp',
			'expm1',
			'f16round',
			'floor',
			'fround',
			'hypot',
			'imul',
			'log',
			'log10',
			'log1p',
			'log2',
			'max',
			'min',
			'pow',
			'random',
			'round',
			'sign',
			'sin',
			'sinh',
			'sqrt',
			'sumPrecise',
			'tan',
			'tanh',
			'trunc',
		],
		staticProperties: [
			'E',
			'LN10',
			'LN2',
			'LOG10E',
			'LOG2E',
			'PI',
			'SQRT1_2',
			'SQRT2',
		],
	},
	NaN: {
		globals: ['NaN'],
		instanceMethods: [],
		staticMethods: [],
	},
	Number: {
		globals: ['Number'],
		instanceMethods: [
			'toExponential',
			'toFixed',
			'toLocaleString',
			'toPrecision',
			'toString',
			'valueOf',
		],
		staticMethods: [
			'isFinite',
			'isInteger',
			'isNaN',
			'isSafeInteger',
			'parseFloat',
			'parseInt',
		],
		staticProperties: [
			'EPSILON',
			'MAX_SAFE_INTEGER',
			'MAX_VALUE',
			'MIN_SAFE_INTEGER',
			'MIN_VALUE',
			'NaN',
			'NEGATIVE_INFINITY',
			'POSITIVE_INFINITY',
		],
	},
	Object: {
		globals: ['Object'],
		instanceMethods: [
			'hasOwnProperty',
			'isPrototypeOf',
			'propertyIsEnumerable',
			'toLocaleString',
			'toString',
			'valueOf',
		],
		staticMethods: [
			'assign',
			'create',
			'defineProperties',
			'defineProperty',
			'entries',
			'freeze',
			'fromEntries',
			'getOwnPropertyDescriptor',
			'getOwnPropertyDescriptors',
			'getOwnPropertyNames',
			'getOwnPropertySymbols',
			'getPrototypeOf',
			'groupBy',
			'hasOwn',
			'is',
			'isExtensible',
			'isFrozen',
			'isSealed',
			'keys',
			'preventExtensions',
			'seal',
			'setPrototypeOf',
			'values',
		],
	},
	parseFloat: {
		globals: ['parseFloat'],
		instanceMethods: [],
		staticMethods: [],
	},
	parseInt: {
		globals: ['parseInt'],
		instanceMethods: [],
		staticMethods: [],
	},
	Promise: {
		globals: ['Promise'],
		instanceMethods: [
			'catch',
			'finally',
			'then',
		],
		staticMethods: [
			'all',
			'allSettled',
			'any',
			'race',
			'reject',
			'resolve',
			'try',
			'withResolvers',
		],
	},
	Proxy: {
		globals: ['Proxy'],
		instanceMethods: [],
		staticMethods: ['revocable'],
	},
	RangeError: {
		globals: ['RangeError'],
		instanceMethods: [],
		staticMethods: [],
	},
	ReferenceError: {
		globals: ['ReferenceError'],
		instanceMethods: [],
		staticMethods: [],
	},
	Reflect: {
		globals: ['Reflect'],
		instanceMethods: [],
		staticMethods: [
			'apply',
			'construct',
			'defineProperty',
			'deleteProperty',
			'get',
			'getOwnPropertyDescriptor',
			'getPrototypeOf',
			'has',
			'isExtensible',
			'ownKeys',
			'preventExtensions',
			'set',
			'setPrototypeOf',
		],
	},
	RegExp: {
		globals: ['RegExp'],
		instanceMethods: [
			'exec',
			'test',
			'toString',
		],
		instanceProperties: [
			'dotAll',
			'flags',
			'global',
			'hasIndices',
			'ignoreCase',
			'multiline',
			'source',
			'sticky',
			'unicode',
			'unicodeSets',
		],
		staticMethods: ['escape'],
	},
	Set: {
		globals: ['Set'],
		instanceMethods: [
			'add',
			'clear',
			'delete',
			'difference',
			'entries',
			'forEach',
			'has',
			'intersection',
			'isDisjointFrom',
			'isSubsetOf',
			'isSupersetOf',
			'keys',
			'symmetricDifference',
			'union',
			'values',
		],
		instanceProperties: ['size'],
		staticMethods: [],
	},
	SharedArrayBuffer: {
		globals: ['SharedArrayBuffer'],
		instanceMethods: [
			'grow',
			'slice',
		],
		instanceProperties: [
			'byteLength',
			'growable',
			'maxByteLength',
		],
		staticMethods: [],
	},
	String: {
		globals: ['String'],
		instanceMethods: [
			'at',
			'charAt',
			'charCodeAt',
			'codePointAt',
			'concat',
			'endsWith',
			'includes',
			'indexOf',
			'isWellFormed',
			'lastIndexOf',
			'localeCompare',
			'match',
			'matchAll',
			'normalize',
			'padEnd',
			'padStart',
			'repeat',
			'replace',
			'replaceAll',
			'search',
			'slice',
			'split',
			'startsWith',
			'substring',
			'toLocaleLowerCase',
			'toLocaleUpperCase',
			'toLowerCase',
			'toString',
			'toUpperCase',
			'toWellFormed',
			'trim',
			'trimEnd',
			'trimStart',
			'valueOf',
		],
		staticMethods: [
			'fromCharCode',
			'fromCodePoint',
			'raw',
		],
	},
	Symbol: {
		globals: ['Symbol'],
		instanceMethods: [
			'description',
			'toString',
			'valueOf',
		],
		staticMethods: [
			'for',
			'keyFor',
		],
		wellKnownSymbols: [
			'asyncIterator',
			'hasInstance',
			'isConcatSpreadable',
			'iterator',
			'match',
			'matchAll',
			'replace',
			'search',
			'species',
			'split',
			'toPrimitive',
			'toStringTag',
			'unscopables',
		],
	},
	SyntaxError: {
		globals: ['SyntaxError'],
		instanceMethods: [],
		staticMethods: [],
	},
	TypedArray: {
		globals: [
			'BigInt64Array',
			'BigUint64Array',
			'Float16Array',
			'Float32Array',
			'Float64Array',
			'Int8Array',
			'Int16Array',
			'Int32Array',
			'Uint8Array',
			'Uint8ClampedArray',
			'Uint16Array',
			'Uint32Array',
		],
		instanceMethods: [
			'at',
			'copyWithin',
			'entries',
			'every',
			'fill',
			'filter',
			'find',
			'findIndex',
			'findLast',
			'findLastIndex',
			'forEach',
			'includes',
			'indexOf',
			'join',
			'keys',
			'lastIndexOf',
			'map',
			'reduce',
			'reduceRight',
			'reverse',
			'set',
			'slice',
			'some',
			'sort',
			'subarray',
			'toLocaleString',
			'toReversed',
			'toSorted',
			'toString',
			'values',
			'with',
		],
		instanceProperties: [
			'buffer',
			'byteLength',
			'byteOffset',
			'length',
		],
		staticMethods: [
			'from',
			'of',
		],
	},
	TypeError: {
		globals: ['TypeError'],
		instanceMethods: [],
		staticMethods: [],
	},
	undefined: {
		globals: ['undefined'],
		instanceMethods: [],
		staticMethods: [],
	},
	URIError: {
		globals: ['URIError'],
		instanceMethods: [],
		staticMethods: [],
	},
	WeakMap: {
		globals: ['WeakMap'],
		instanceMethods: [
			'delete',
			'get',
			'has',
			'set',
		],
		staticMethods: [],
	},
	WeakRef: {
		globals: ['WeakRef'],
		instanceMethods: ['deref'],
		staticMethods: [],
	},
	WeakSet: {
		globals: ['WeakSet'],
		instanceMethods: [
			'add',
			'delete',
			'has',
		],
		staticMethods: [],
	},
};

// Build lookup maps for efficient querying
/** @type {Set<string>} */
export const allGlobals = new Set();
/** @type {Map<string, string[]>} methodName -> [categoryNames] */
export const allStaticMethods = new Map();
/** @type {Map<string, string[]>} methodName -> [categoryNames] */
export const allInstanceMethods = new Map();
/** @type {Map<string, string>} globalName -> categoryName */
export const globalToCategory = new Map();

for (const [category, info] of Object.entries(primordials)) {
	for (const global of info.globals) {
		allGlobals.add(global);
		globalToCategory.set(global, category);
	}

	for (const method of info.staticMethods) {
		if (!allStaticMethods.has(method)) {
			allStaticMethods.set(method, []);
		}
		allStaticMethods.get(method)?.push(category);
	}

	for (const method of info.instanceMethods) {
		if (!allInstanceMethods.has(method)) {
			allInstanceMethods.set(method, []);
		}
		allInstanceMethods.get(method)?.push(category);
	}
}

// TypedArray globals for type checking
export const typedArrayGlobals = new Set(primordials.TypedArray.globals);

// Methods that exist on multiple types and need type disambiguation
/** @type {Set<string>} */
export const ambiguousInstanceMethods = new Set();
for (const [method, categories] of allInstanceMethods) {
	if (categories.length > 1) {
		ambiguousInstanceMethods.add(method);
	}
}
